import { quoteIdent } from "@nia/extract/mssql";

/**
 * `nia-agent sql readonly` (docs/plans/planometry-integration.md Phase 3
 * prep): generates SQL Server 2008-compatible T-SQL that creates one
 * read-only login with access to an explicit list of databases — for a
 * GMS DBA to review and run themselves, never executed by the agent.
 *
 * Only ever grants read-only rights: `db_datareader` + `VIEW DEFINITION`
 * per database (so INFORMATION_SCHEMA introspection works), plus
 * server-scoped `VIEW SERVER STATE` (so `sys.dm_exec_requests` is visible
 * for cancel-confirmation — see packages/extract/src/mssql's
 * `queryTextRunning` pattern). No write role or grant is ever emitted.
 *
 * The password is always a placeholder — this function never accepts or
 * emits a real password, so a generated script can never leak one into
 * logs or source control.
 */

const IDENTIFIER_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/;

export class InvalidIdentifierError extends Error {
  constructor(
    public readonly kind: string,
    public readonly value: string,
  ) {
    super(`invalid ${kind} ${JSON.stringify(value)}: must match ${IDENTIFIER_PATTERN}`);
  }
}

export interface BuildReadonlySetupScriptInput {
  loginName: string;
  /** One database per entry — a server-wide login is still created once, but each database needs its own CREATE USER/grants (one connection = one database, per the extract module's design). */
  databases: string[];
  /** When set, grants are scoped to this one schema only (`GRANT SELECT`/`GRANT VIEW DEFINITION ON SCHEMA::<schema>`) instead of database-wide `db_datareader` + `VIEW DEFINITION`. */
  schema?: string;
  /** Opt-in, off by default: grants server-scoped `VIEW SERVER STATE` (needed for `sys.dm_exec_requests` cancel-confirmation visibility — see `agent doctor`'s check). Many DBAs won't want a server-scoped grant at all, so this is never emitted unless explicitly requested. */
  withCancelVisibility?: boolean;
}

function assertIdentifier(kind: string, value: string): void {
  if (!IDENTIFIER_PATTERN.test(value)) throw new InvalidIdentifierError(kind, value);
}

export function buildReadonlySetupScript(input: BuildReadonlySetupScriptInput): string {
  assertIdentifier("login name", input.loginName);
  if (input.databases.length === 0) throw new Error("databases must not be empty");
  for (const db of input.databases) assertIdentifier("database name", db);
  if (input.schema !== undefined) assertIdentifier("schema name", input.schema);

  const login = quoteIdent(input.loginName);
  const loginLiteral = sqlStringLiteral(input.loginName);
  const schemaIdent = input.schema !== undefined ? quoteIdent(input.schema) : undefined;

  const cancelVisibilityGrant = input.withCancelVisibility
    ? `
-- Required for sys.dm_exec_requests visibility (confirms a cancelled
-- query actually stopped) — a read-only server-state view permission,
-- not a write right. Opt-in via --with-cancel-visibility.
GRANT VIEW SERVER STATE TO ${login};
`
    : `
-- VIEW SERVER STATE was NOT granted (opt-in only, via
-- --with-cancel-visibility). Without it, \`agent doctor\`'s cancel-
-- confirmation check (sys.dm_exec_requests) will show a WARNING, not a
-- failure — the agent still works, it just can't confirm a cancelled
-- query actually stopped server-side.
`;

  const header = `-- Generated by \`nia-agent sql readonly\` — review before running.
-- Creates ONE read-only SQL Server login with access to the databases
-- listed below${schemaIdent ? ` (schema ${schemaIdent} only)` : ""}. No write
-- role or permission is ever granted by this script (no db_datawriter,
-- no INSERT/UPDATE/DELETE/ALTER/CONTROL, no db_owner). Safe to re-run
-- (every statement is idempotent).
--
-- The password below is a PLACEHOLDER ONLY. Set a real, strong password
-- before running this script (e.g. edit it interactively in SSMS/sqlcmd)
-- and never commit or log the real value.
-- Compatible with SQL Server 2008 and later (no TRY_CAST/CONCAT/FORMAT/
-- IIF/OFFSET-FETCH/STRING_SPLIT or other 2012+ syntax).

USE [master];
IF NOT EXISTS (SELECT 1 FROM sys.server_principals WHERE name = ${loginLiteral})
BEGIN
  CREATE LOGIN ${login} WITH PASSWORD = N'<CHANGE_ME_STRONG_PASSWORD>', CHECK_EXPIRATION = OFF, CHECK_POLICY = ON;
END;
${cancelVisibilityGrant}`;

  const perDatabase = input.databases
    .map((db) => {
      const dbIdent = quoteIdent(db);
      const grants = schemaIdent
        ? `GRANT SELECT ON SCHEMA::${schemaIdent} TO ${login};
GRANT VIEW DEFINITION ON SCHEMA::${schemaIdent} TO ${login};`
        : `EXEC sp_addrolemember N'db_datareader', ${loginLiteral};
GRANT VIEW DEFINITION TO ${login};`;
      return `
USE ${dbIdent};
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = ${loginLiteral})
BEGIN
  CREATE USER ${login} FOR LOGIN ${login};
END;
${grants}
`;
    })
    .join("");

  const footer = schemaIdent
    ? `
-- No write rights were granted anywhere above: ${login} can read table/
-- view data and metadata within schema ${schemaIdent} only (SELECT +
-- VIEW DEFINITION scoped to that schema)${input.withCancelVisibility ? " and view server-state DMVs (VIEW SERVER STATE)" : ""}, and nothing else.
-- Tables/views in other schemas are NOT readable by this login.
`
    : `
-- No write rights were granted anywhere above: ${login} can read table/
-- view data and metadata (db_datareader + VIEW DEFINITION)${input.withCancelVisibility ? " and view server-state DMVs (VIEW SERVER STATE)" : ""}, and nothing else.
`;

  return header + perDatabase + footer;
}

function sqlStringLiteral(value: string): string {
  return `N'${value.replace(/'/g, "''")}'`;
}
