import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { connect, introspectCatalog } from "@nia/extract/mssql";
import { buildReadonlySetupScript } from "./sqlReadonlyScript.js";

/**
 * Mandatory Phase 3 prep integration test: proves the SQL generated by
 * `buildReadonlySetupScript` actually works against a real SQL Server —
 * the login it creates can read, can see the catalog, can use
 * sys.dm_exec_requests, and genuinely cannot write. Requires the
 * throwaway harness running first: packages/extract/scripts/harness/start.sh
 * Excluded from `pnpm test` (vitest.config.ts); run explicitly with
 * `pnpm test:integration`.
 */

const HOST = process.env.NIA_EXTRACT_MSSQL_HOST ?? "localhost";
const PORT = Number(process.env.NIA_EXTRACT_MSSQL_PORT ?? "14330");
const SA_USER = process.env.NIA_EXTRACT_MSSQL_USER ?? "sa";
const SA_PASSWORD = process.env.NIA_EXTRACT_MSSQL_PASSWORD ?? "N!aExtractTest_2026";
const DATABASE = process.env.NIA_EXTRACT_MSSQL_DATABASE ?? "nia_extract_test";

const TEST_LOGIN = "nia_readonly_itest";
// Throwaway test-container password only, torn down with the login at the
// end of this suite — not a real secret.
const TEST_PASSWORD = "N!aReadonlyItest_2026";

type Pool = Awaited<ReturnType<typeof connect>>;

async function dropTestLogin(pool: Pool): Promise<void> {
  await pool.request().batch(`
    USE ${sqlBracket(DATABASE)};
    IF EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'${TEST_LOGIN}')
      DROP USER ${sqlBracket(TEST_LOGIN)};
    USE [master];
    IF EXISTS (SELECT 1 FROM sys.server_principals WHERE name = N'${TEST_LOGIN}')
      DROP LOGIN ${sqlBracket(TEST_LOGIN)};
  `);
}

function sqlBracket(name: string): string {
  return `[${name.replace(/]/g, "]]")}]`;
}

describe("buildReadonlySetupScript against a real SQL Server", () => {
  let saPool: Pool;

  beforeAll(async () => {
    saPool = await connect({ server: HOST, port: PORT, database: DATABASE, user: SA_USER, password: SA_PASSWORD, encrypt: false });
    await dropTestLogin(saPool); // clean slate in case a previous run left the login behind
  });

  afterAll(async () => {
    await dropTestLogin(saPool);
    await saPool.close();
  });

  it("creates a login that can read, see the catalog, use sys.dm_exec_requests, and cannot write", async () => {
    const script = buildReadonlySetupScript({ loginName: TEST_LOGIN, databases: [DATABASE] }).replace("<CHANGE_ME_STRONG_PASSWORD>", TEST_PASSWORD);
    await saPool.request().batch(script);

    const userPool = await connect({ server: HOST, port: PORT, database: DATABASE, user: TEST_LOGIN, password: TEST_PASSWORD, encrypt: false });
    try {
      // Can read + can see the catalog.
      const catalog = await introspectCatalog(userPool, "UTC");
      expect(catalog.tables.length).toBeGreaterThan(0);
      expect(catalog.tables.some((t) => t.name === "dbo.widgets")).toBe(true);

      // sys.dm_exec_requests is visible (VIEW SERVER STATE worked).
      const dmvResult = await userPool.request().query<{ c: number }>("SELECT COUNT(*) AS c FROM sys.dm_exec_requests");
      expect(dmvResult.recordset[0]?.c).toBeGreaterThanOrEqual(0);

      // Cannot write: an INSERT against an existing table is rejected.
      await expect(userPool.request().query("INSERT INTO dbo.widgets (name, notes, is_active, price, exact_decimal, cash, big, event_date, created_at, created_at_offset, legacy_dt, small_dt, duration, ratio, uid) VALUES ('x', NULL, 1, 1, 1, 1, 1, '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01', '00:00:00', 1, NEWID())")).rejects.toThrow(/permission|denied/i);

      // Cannot write: creating a new table is rejected too.
      await expect(userPool.request().query("CREATE TABLE dbo.nia_readonly_itest_probe (id INT)")).rejects.toThrow(/permission|denied/i);
    } finally {
      await userPool.close();
    }
  });
});
