/**
 * Shared shape + load logic for the agent download manifest
 * (apps/agent/packaging/manifest.json, generated by
 * apps/agent/packaging/generate-manifest.mjs) — consumed by both
 * apps/web (apps/web/src/lib/downloads/manifest.ts, browser-facing
 * download links) and services/agent-bridge (the agent-authenticated
 * `GET /agent-api/update` route, Phase 6 polish) so the "read
 * AGENT_DOWNLOADS_BASE_URL if set, else fall back to the local
 * packaging/manifest.json on disk" rule lives in exactly one place.
 *
 * Each caller still supplies its own `packagingRoot` (the local fallback
 * path) since apps/web and services/agent-bridge have different runtime
 * cwd's and therefore different relative hops to apps/agent/packaging.
 */
import fs from "node:fs/promises";
import path from "node:path";

export type AgentOs = "windows" | "macos" | "linux";

export type DownloadManifestFile = {
  name: string;
  os: AgentOs;
  kind: "primary" | "advanced";
  size: number;
  sha256: string;
};

export type DownloadManifest = {
  version: string;
  generatedAt: string;
  files: DownloadManifestFile[];
};

export function getDownloadsBaseUrl(): string | undefined {
  return process.env.AGENT_DOWNLOADS_BASE_URL || undefined;
}

/**
 * `packagingRoot` is only consulted when `AGENT_DOWNLOADS_BASE_URL` is
 * unset (local dev) — it must point at the directory containing
 * `manifest.json` directly (i.e. `apps/agent/packaging`, not one of its
 * per-OS `dist/` subfolders).
 */
export async function loadDownloadManifest(packagingRoot: string): Promise<DownloadManifest> {
  const base = getDownloadsBaseUrl();
  if (base) {
    const res = await fetch(`${base.replace(/\/$/, "")}/manifest.json`, { cache: "no-store" });
    if (!res.ok) {
      throw new Error(`failed to fetch agent download manifest: ${res.status}`);
    }
    return (await res.json()) as DownloadManifest;
  }
  const raw = await fs.readFile(path.join(packagingRoot, "manifest.json"), "utf8");
  return JSON.parse(raw) as DownloadManifest;
}

/**
 * Picks the one `kind: "primary"` file for `os` out of a manifest's
 * `files[]` — the installer end-users/agents actually want, as opposed
 * to an `"advanced"` (e.g. service-only/no-desktop) alternate build.
 */
export function findPrimaryManifestFile(manifest: DownloadManifest, os: AgentOs): DownloadManifestFile | undefined {
  return manifest.files.find((file) => file.os === os && file.kind === "primary");
}
