import { describe, expect, it } from "vitest";
import { buildUpsertSql } from "./writeSql.js";

describe("buildUpsertSql", () => {
  it("builds a single-row UPSERT with DO UPDATE SET for non-key columns", () => {
    const sql = buildUpsertSql({ namespace: "sales", name: "orders" }, ["id", "total", "status"], ["id"], 1);
    expect(sql).toBe(
      'INSERT INTO "sales"."orders" ("id", "total", "status") OVERRIDING SYSTEM VALUE VALUES ($1, $2, $3) ON CONFLICT ("id") DO UPDATE SET "total" = excluded."total", "status" = excluded."status"',
    );
  });

  it("builds a multi-row VALUES list with sequential, non-overlapping placeholders", () => {
    const sql = buildUpsertSql({ namespace: "sales", name: "orders" }, ["id", "total"], ["id"], 3);
    expect(sql).toBe(
      'INSERT INTO "sales"."orders" ("id", "total") OVERRIDING SYSTEM VALUE VALUES ($1, $2), ($3, $4), ($5, $6) ON CONFLICT ("id") DO UPDATE SET "total" = excluded."total"',
    );
  });

  it("falls back to DO NOTHING when every column is an upsert key (nothing left to update)", () => {
    const sql = buildUpsertSql({ namespace: "sales", name: "orders" }, ["id", "sku"], ["id", "sku"], 1);
    expect(sql).toBe('INSERT INTO "sales"."orders" ("id", "sku") OVERRIDING SYSTEM VALUE VALUES ($1, $2) ON CONFLICT ("id", "sku") DO NOTHING');
  });

  it("quotes identifiers containing double quotes to prevent injection via identifier fields", () => {
    const sql = buildUpsertSql({ namespace: 'sa"les', name: "orders" }, ["id"], ["id"], 1);
    expect(sql).toContain('"sa""les"');
  });

  // Check item 1 (identity columns): a mapped column that's GENERATED
  // ALWAYS AS IDENTITY on dest rejects an explicit (non-DEFAULT) value
  // without this clause — confirmed live against dev-postgres both that
  // the clause is required for GENERATED ALWAYS and that it's a harmless
  // no-op otherwise (plain columns, GENERATED BY DEFAULT).
  it("always includes OVERRIDING SYSTEM VALUE so an explicit id survives a GENERATED ALWAYS AS IDENTITY destination column", () => {
    const sql = buildUpsertSql({ namespace: "public", name: "users" }, ["id", "name"], ["id"], 1);
    expect(sql).toContain('OVERRIDING SYSTEM VALUE');
  });
});
