#!/usr/bin/env node
// Writes src/generated/version.ts from package.json's version field, so the
// same literal is available to every packaging target (Docker/Linux tsc
// output, and the Windows single-executable build, which has no adjacent
// package.json to read at runtime) via one plain import, not a runtime
// fs read. Re-run on every build/test — cheap, idempotent.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const outDir = path.join(root, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  path.join(outDir, "version.ts"),
  `// Generated by scripts/generate-version.mjs — do not edit by hand.\nexport const AGENT_VERSION = ${JSON.stringify(pkg.version)};\n`,
);
